---
name: 'Import New Actions Firewall Exceptions'
on:
  schedule:
    - cron: '17 2 * * 0'
env:
  FIREWALL_FILE: github-actions-subnets.txt
jobs:
  build_ip_list:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v2

    - name: 'Obtain meta info from API and update file'
      run: 'curl --silent -H "Accept: application/vnd.github.v3+json" https://api.github.com/meta | jq -r ".actions[]" >> $FIREWALL_FILE'
      shell: bash

    - name: 'Commit any files changed'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Automated update'